version: 2

submodules:
  include: all

sphinx:
  configuration: docs_sphinx/conf.py

build:
  os: "ubuntu-20.04"
  tools:
    python: "3"  # latest stable CPython
  jobs:
    post_checkout:
      - git fetch --unshallow || true
      - git fetch --all --tags || true
    post_install:
        - python -m pip install .
        - python -m pip install -r rtd-requirements.txt
