package:
  name: brian2
  version: "2.1.2+git"

# Note: specifying a minimal version for numyp leads to incorrect build strings
requirements:
  build:
    - python
    - cython >=0.18
    - setuptools >=6.0
    - numpy 1.10  # we build against the oldest supported version

  run:
    - python
    - numpy >=1.10  # newer versions are still ABI-compatible
    - sympy >=0.7.6,!=1.1.0
    - pyparsing
    - scipy >=0.13.3
    - weave # [py2k]
    - bsddb # [py2k and not win]
    - gsl >1.15
    - cython >=0.18
    - jinja2 >=2.7
    - setuptools >=6.0
    - py-cpuinfo >=0.1.6

test:
  # Python imports
  imports:
    - brian2
    - brian2.codegen
    - brian2.codegen.generators
    - brian2.codegen.runtime
    - brian2.codegen.runtime.cython_rt
    - brian2.codegen.runtime.numpy_rt
    - brian2.codegen.runtime.weave_rt
    - brian2.core
    - brian2.devices
    - brian2.devices.cpp_standalone
    - brian2.equations
    - brian2.groups
    - brian2.input
    - brian2.memory
    - brian2.monitors
    - brian2.parsing
    - brian2.spatialneuron
    - brian2.sphinxext
    - brian2.stateupdaters
    - brian2.synapses
    - brian2.tests
    - brian2.tests.features
    - brian2.units
    - brian2.utils

  commands:
    #- python -c 'import brian2; brian2.test()'

  requires:
    - nose

source:
  path: ../..

build:
  script: python setup.py install --with-cython --fail-on-error --single-version-externally-managed --record=record.txt

about:
  home: http://www.briansimulator.org/
  dev_url: https://github.com/brian-team/brian2
  doc_url: http://brian2.readthedocs.io/
  license: CeCILL-2.1
  license_file: LICENSE
  summary: 'A clock-driven simulator for spiking neural networks'
